version: "3"
services:
  nginx:
      build:
        context: ./nginx-plus
        dockerfile: Dockerfile
      image: nginx-plus-njs:latest
      volumes:
          - ./nginx-plus/nginx/templates:/etc/nginx/templates
          - ./nginx-plus/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx-plus/nginx/conf.d:/etc/nginx/conf.d
      ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
      environment:
        - NJS=njs.test
